### ISSUE TITLE
demo_server error in handling tts request. 

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mimic2#23]
Current (git pull returns Already up-to-date) mimic2, custom model, python3.6, flask1.0.2, tf1.9.  On the client end, https://github.com/MycroftAI/mycroft-core/blob/3e6dedbbcc236c5fee35e7180ecafcf0a46eddda/mycroft/tts/mimic2_tts.py#L223 edited to remove the visemes add-on piece. 
Asking mycroft "what time is it?" returns the correct time, but the TTS attempt results in the following on the demo_server instance: 

```[2018-11-25 02:00:20,377] ERROR in app: Exception on /synthesize [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "demo_server.py", line 75, in get
    text =  " ".join(replace_acronym(custom_splitter(text)))
  File "/opt/mimic2/synthesize_helper.py", line 56, in custom_splitter
    if "{" in text and "}" in text:
TypeError: argument of type 'NoneType' is not iterable
192.168.10.101 - - [25/Nov/2018 02:00:20] "GET /synthesize?test=two%20o%27clock. HTTP/1.1" 500 -
192.168.10.244 - - [25/Nov/2018 02:00:35] "GET /synthesize?text=two%20o%27clock. HTTP/1.1" 200 -
```

**Comment by el-tocino** [comment]
Ack. Derp. test/text.  Closing.
