### ISSUE TITLE
No such file or directory avconv

### ISSUE THREAD

**Issue by ahvahsky2008** [MycroftAI/mimic2#30]
Use manual from main page. How solve it?

```
root@508f20df7aee:~/mimic2# python3 preprocess.py --dataset ljspeech
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Hyperparameters:
  adam_beta1: 0.9
  adam_beta2: 0.999
  batch_size: 32
  cleaners: english_cleaners
  embedding_dim: 512
  frame_length_ms: 50
  frame_shift_ms: 12.5
  griffin_lim_iters: 50
  initial_learning_rate: 0.0015
  learning_rate_decay_halflife: 100000
  max_iters: 200
  max_mel_freq: 7600
  min_level_db: -100
  min_mel_freq: 125
  num_freq: 1025
  num_mels: 80
  outputs_per_step: 5
  power: 1.5
  ref_level_db: 20
  sample_rate: 22000
  trim_fft_size: 1024
  trim_hop_size: 256
  trim_top_db: 40
  use_cmudict: False
  0%|                                                                                         | 0/13100 [00:00<?, ?it/s]concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/root/mimic2/datasets/ljspeech.py", line 53, in _process_utterance
    wav = audio.load_wav(wav_path)
  File "/root/mimic2/util/audio.py", line 10, in load_wav
    return librosa.core.load(path, sr=hparams.sample_rate)[0]
  File "/usr/local/lib/python3.5/dist-packages/librosa/core/audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/usr/local/lib/python3.5/dist-packages/audioread/__init__.py", line 107, in audio_open
    backends = available_backends()
  File "/usr/local/lib/python3.5/dist-packages/audioread/__init__.py", line 86, in available_backends
    if ffdec.available():
  File "/usr/local/lib/python3.5/dist-packages/audioread/ffdec.py", line 108, in available
    creationflags=PROC_FLAGS,
  File "/usr/local/lib/python3.5/dist-packages/audioread/ffdec.py", line 94, in popen_multiple
    return subprocess.Popen(cmd, *args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'avconv'
"""
```

**Comment by el-tocino** [comment]
Might need to be installed. What distro/version are you running?

**Comment by Simonmicro** [comment]
...for me: The docker file - uninstalled tensorflow because of `Illegal instruction (core dumped)` error and reinstalled version 1.5 of tensorflow. Maybe the dockerfile is not correct for building LJSpeech-1.1.
